# Generated by Django 5.1.5 on 2025-01-25 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='image',
            new_name='restaurant_image',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='address',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='per_table_cost',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='table_ac',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='table_non_ac',
        ),
        migrations.AddField(
            model_name='customuser',
            name='favorite_restaurant',
            field=models.ManyToManyField(blank=True, related_name='favorite_restaurant', to='home.restaurant'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='food_image',
            field=models.ImageField(blank=True, null=True, upload_to='food_images/'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='other_image',
            field=models.ImageField(blank=True, null=True, upload_to='other_images/'),
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop', models.TextField()),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('pincode', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='home.restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='BankDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_mane', models.CharField(max_length=100)),
                ('account_no', models.CharField(max_length=20)),
                ('ifsc_code', models.CharField(max_length=20)),
                ('bank_name', models.CharField(max_length=100)),
                ('upi_id', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='home.restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_capacity', models.PositiveIntegerField()),
                ('table_no', models.PositiveIntegerField()),
                ('is_ac', models.BooleanField(default=False)),
                ('is_reserved', models.BooleanField(default=False)),
                ('reservation_date', models.DateField()),
                ('reservation_time', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='home.restaurant')),
            ],
        ),
    ]
