# Generated by Django 5.1.5 on 2025-08-09 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='restaurant_image',
            field=models.FileField(blank=True, max_length=200, null=True, upload_to='public/resturant_images/'),
        ),
    ]
