# Generated by Django 5.1.5 on 2025-02-02 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='restaurant_image_url',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='restaurant_image',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='resturant_images/'),
        ),
    ]
