# Generated by Django 5.1.5 on 2025-02-02 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_restaurant_restaurant_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='restaurant_image',
            field=models.FileField(blank=True, max_length=200, null=True, upload_to='resturant_images/'),
        ),
    ]
