# Generated by Django 5.1.5 on 2025-08-09 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_restaurant_restaurant_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='restaurant_image',
            field=models.FileField(blank=True, max_length=200, null=True, upload_to='staticfiles/resturant_images/'),
        ),
    ]
