# Generated by Django 5.1.5 on 2025-01-26 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_image_restaurant_restaurant_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='restaurant_image',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='restaurant_image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
