# Generated by Django 5.1.5 on 2025-01-26 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_restaurant_restaurant_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='restaurant_image_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
