# Generated by Django 5.1.5 on 2025-02-02 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_restaurant_restaurant_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='username',
            field=models.CharField(blank=True, default='None', max_length=100, null=True),
        ),
    ]
