# Generated by Django 5.1.5 on 2025-02-02 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_customuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='owner_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
